# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greeting_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_StartWidget(object):
    def setupUi(self, StartWidget):
        StartWidget.setObjectName("StartWidget")
        StartWidget.resize(400, 173)
        self.input_field = QtWidgets.QLineEdit(StartWidget)
        self.input_field.setGeometry(QtCore.QRect(30, 40, 351, 21))
        self.input_field.setObjectName("input_field")
        self.enter_button = QtWidgets.QPushButton(StartWidget)
        self.enter_button.setGeometry(QtCore.QRect(120, 90, 151, 51))
        self.enter_button.setObjectName("enter_button")

        self.retranslateUi(StartWidget)
        QtCore.QMetaObject.connectSlotsByName(StartWidget)

    def retranslateUi(self, StartWidget):
        _translate = QtCore.QCoreApplication.translate
        StartWidget.setWindowTitle(_translate("StartWidget", "Form"))
        self.input_field.setPlaceholderText(_translate("StartWidget", "Введите путь до датасета (.csv файл)"))
        self.enter_button.setText(_translate("StartWidget", "Ввод"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartWidget = QtWidgets.QWidget()
    ui = Ui_StartWidget()
    ui.setupUi(StartWidget)
    StartWidget.show()
    sys.exit(app.exec_())
